### PR TITLE
fix well layers rendering artifacts

### LINKED ISSUE #268: Error when rendering hole/casing of approaching 0 length
**Describe the bug**
Get an unintelligible error from Pixi when trying to render a hole or casing of length shorter or equal to `StaticWellboreBaseComponentIncrement`.

**To Reproduce**
1. Clone https://github.com/ooystein/esv-intersection/tree/issue/hole-casing-cement-shorter-than-static-increment
2. Run storybook
3. Open intersection story http://localhost:6006/?path=/story/intersection--intersection

PS.
In the branch reproducing the bug I have added both a hole and a casing of length 0

### PR DESCRIPTION
**Pull request by ooystein**
- Simplify createNormal and offsetPoints
- Get normals from curve-interpolator
- Add esModuleInterop to tsconfig.json to load Vector2 in Jest tests
- Cache curtain path
- Optimized path generator for hole, casing, and cement
- Simplify shoe render
- Optimize drawing of cement by using pixi.js SimpleRope. This also fixes the texure for cement so it streches/warps along the cement path.
- Optimize drawing of hole and casing by dropping the mask. Create textures of correct width so mask is redundant.
- Remove unneeded interpolation from createOffsetCoords()
- Remove unneeded actualPoints()
- Fix memory leak where Graphics object was not deleted after use. (This is still not optimal. The layers should update the graphics objects and not create new on every frame. Creating new graphics objects on every frame makes for easy memory leaks and unnecessary overhead.)

Closes #268

### CODE REVIEW

**Comment by ooystein** [comment]
Now that Vector2 is available in tests we can uncomment some tests from `reference-system.test.ts`.

File: src/datautils/wellboreItemShapeGenerator.ts [hunk 1]
```diff
@@ -1,78 +1,116 @@
...
-  return res.length > 0 ? res[0] : {};
+export const parseCement = (cement: Cement, casings: Casing[], holes: HoleSize[]): CompiledCement => {
+  const attachedCasing = findCasing(cement.casingId, casings);
+  const res: CompiledCement = {
+    ...cement,
+    boc: attachedCasing.end,
+    attachedCasing,
+    intersectingItems: findIntersectingItems(cement, attachedCasing, casings, holes),
+  };
+  return res;
```
Comment (andreabrambilla) [inline src/datautils/wellboreItemShapeGenerator.ts:54]: This name is a bit unfortunate, it is not very obvious what this function is doing. The only clear thing is that it is creating a `CompiledCement` out of a `Cement`, so maybe let's name it `compileCement` or something along those lines

File: src/datautils/wellboreItemShapeGenerator.ts [hunk 2]
```diff
@@ -1,78 +1,116 @@
...
+      const bDim = b.innerDiameter ? b.innerDiameter : b.diameter;
+      return aDim - bDim;
+    }) // ascending
+    .find((object) => object.start <= depth && object.end >= depth);
+
+  const outerDiameter = outerObjectAtDepth
+    ? outerObjectAtDepth.innerDiameter
+      ? outerObjectAtDepth.innerDiameter
+      : outerObjectAtDepth.diameter - HOLE_OUTLINE
+    : defaultCementWidth;
```
Comment (andreabrambilla) [inline src/datautils/wellboreItemShapeGenerator.ts:109]: I assume the check for `innerDiameter` on line 106 is used to distinguish between holes and casings. Is there any other method to check for this, that is possibly more self explaining? If not, then let's just add a comment about that

File: src/interfaces.ts [hunk 3]
```diff
@@ -149,24 +152,18 @@ export interface Cement {
...
-  points: MDPoint[];
-  hasShoe?: boolean;
-  innerDiameter?: number;
-}
-
 export interface WellItemGraphics {
   graphics: Graphics;
 }
 
 export interface NormalCoordsObject {
```
Comment (andreabrambilla) [inline src/interfaces.ts:163]: IT looks like this interface is not used anymore after your changes, should we just get rid of it?

File: .storybook/src/complete-example/intersection.stories.ts [hunk 4]
```diff
@@ -47,6 +47,7 @@ export const intersection = () => {
   Promise.all(promises).then((values) => {
     const [path, completion, seismic, surfaces, stratColumns, casings, holesizes, cement, picks] = values;
     const referenceSystem = new IntersectionReferenceSystem(path);
+    // referenceSystem.offset = path[0][2]
```
Comment (andreabrambilla) [inline .storybook/src/complete-example/intersection.stories.ts:50]: I guess this should be removed

**Comment by ooystein** [comment]
Some of the new names used are not very good. IntersectionReferenceSystem::curtainTangent() for instance. But as there will be a refactor with new consistent vocabulary based on what is learned from creating a vocabulary in REP I think we can wait on that process for renaming stuff.
